ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ues TEXT[] DEFAULT '{}';

DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT unique_pseudo UNIQUE (pseudo);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE messages ADD COLUMN IF NOT EXISTS seen BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS seen_at TIMESTAMP NULL;
