ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ues TEXT[] DEFAULT '{}';

DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT unique_pseudo UNIQUE (pseudo);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE messages ADD COLUMN IF NOT EXISTS seen BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS seen_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS global_chat_read (
  user_id            INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_msg_id   INTEGER   NOT NULL DEFAULT 0,
  updated_at         TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id)
);
